package com.example.proyectofinal;

public class CaptionAnimales_tierra{
    public static String[] vectorCaracterisicas=new String[]{
            "Soy un animal terrestre que mide aproximadamente 1.2 metros de alto y peso entre 150 y 250 kilos. Soy un cazador carnívoro muy peligroso, y tengo una melena distintiva si soy macho, soy musculoso y tengo garras retráctiles. Vivo en el África Subsahariana. ¿Sabes quién soy?",
            "Elefante Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Tigre Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Oso pardo Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Gorila de montaña Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Jirafa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Rinoceronte Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Zorro rojo Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Bisonte Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Panda Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Cebra Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Canguro Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Lobo Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Koala Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Cocodrilo Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Cobra Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Camello Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Perezoso Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Avestruz Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
            "Armadillo Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et efficitur ipsum, sed blandit felis. Nunc quam nunc, imperdiet lobortis enim vel, facilisis congue turpis. Etiam id purus vel arcu luctus bibendum ac in dolor. Nullam in sodales justo. Donec pretium",
    };
}