package com.example.proyectofinal;

import java.util.ArrayList;
import java.util.Arrays;

public class ListAnimalesAire_aprender {
    public static ArrayList<Animales_aprender> listAnimalesAire_aprender=new ArrayList<>(Arrays.asList(
            new Animales_aprender(
                    1,
                    R.drawable.halcon_peregrino,
                    "Halcón Peregrino",
                    "40-50cm",
                    "0.5-1.5kg",
                    "Baja",
                    "Alas puntiagudas, cabeza oscura (casco), esbelto.",
                    "Distribución Cosmopolita (Global)",
                    "Carnívoro (Aves)",
                    "El animal más rápido del planeta. Alcanza 320km/h en picada."),
            new Animales_aprender(
                    2,
                    R.drawable.aguila_calva,
                    "Águila Calva",
                    "70-100cm",
                    "3-6kg",
                    "Baja",
                    "Envergadura alar de más de 2m, cabeza blanca, pico y garras amarillos.",
                    "Norteamérica (Canadá, EE. UU., México)",
                    "Carnívoro (Peces/Carroña)",
                    "Símbolo nacional de EE. UU. Construye nidos muy grandes."),
            new Animales_aprender(
                    3,
                    R.drawable.condor_andino,
                    "Cóndor Andino",
                    "1.3m",
                    "8-15kg",
                    "Nula",
                    "El ave voladora más grande por área alar (hasta 3.3m). Cabeza calva.",
                    "Cordillera de los Andes (Sudamérica)",
                    "Carroñero",
                    "Ave esencial para limpiar el ambiente de carroña."),
            new Animales_aprender(
                    4,
                    R.drawable.buho_nival,
                    "Búho Nival",
                    "50-65cm",
                    "1.5-3kg",
                    "Baja",
                    "Plumaje blanco denso, ojos amarillos, rapaz diurna.",
                    "Regiones Árticas de Norteamérica y Eurasia",
                    "Carnívoro (Lémures/Roedores)",
                    "Caza de día y de noche. Se camufla perfectamente en la nieve."),
            new Animales_aprender(
                    5,
                    R.drawable.colibri_abeja,
                    "Colibrí Abeja",
                    "5-6cm",
                    "1.6-2g",
                    "Nula",
                    "El ave más pequeña del mundo, iridiscente, vuelo de \"8\".",
                    "Cuba",
                    "Nectarívoro",
                    "Su aleteo es tan rápido que parece un insecto."),
            new Animales_aprender(
                    6,
                    R.drawable.albatros_errante,
                    "Albatros Errante",
                    "1.3m",
                    "6-12kg",
                    "Nula",
                    "La mayor envergadura alar (hasta 3.5m). Plumaje blanco.",
                    "Océano Austral (Atlántico, Pacífico, Índico)",
                    "Carnívoro (Peces/Calamar)",
                    "Pasa la mayor parte de su vida volando sobre el mar."),
            new Animales_aprender(
                    7,
                    R.drawable.murcielago_vamp,
                    "Murciélago Vampiro",
                    "7-9cm",
                    "15-50g",
                    "Baja",
                    "Único mamífero que se alimenta de sangre.",
                    "Centro y Sudamérica",
                    "Hematófago (Sangre)",
                    "Puede transmitir la rabia, pero su mordida en sí es menor."),
            new Animales_aprender(
                    8,
                    R.drawable.golondrina,
                    "Golondrina Común",
                    "17-19cm",
                    "16-22g",
                    "Nula",
                    "Cola bifurcada distintiva, coloración azul metálico, garganta roja.",
                    "Eurasia, África y América",
                    "Carnívoro (Insectívoro)",
                    "Migradora de larga distancia, un clásico de los cielos."),
            new Animales_aprender(
                    9,
                    R.drawable.abeja_melifera,
                    "Abeja Melífera",
                    "10-15mm",
                    "90-125mg",
                    "Baja",
                    "Cuerpo peludo, rayas amarillas y negras, aguijón.",
                    "Global (Introducida en muchos lugares)",
                    "Nectarívoro/Polen",
                    "Insecto social clave en la polinización mundial."),
            new Animales_aprender(
                    10,
                    R.drawable.mariposa_monarca,
                    "Mariposa Monarca",
                    "8.5-12cm (envergadura)",
                    "0.27gr",
                    "Nula",
                    "Coloración naranja y negra brillante.",
                    "América del Norte (Migra a México y California)",
                    "Nectarívoro",
                    "Famosa por su migración masiva de varias generaciones."),
            new Animales_aprender(
                    11,
                    R.drawable.buitre_leonado,
                    "Buitre Leonado",
                    "93-110cm",
                    "6-11kg",
                    "Nula",
                    "Cuello y cabeza sin plumas, garras débiles (no cazan).",
                    "Sur de Europa, Norte de África y Asia",
                    "Carroñero",
                    "Vuelo de planeo impresionante, esencial limpiador del medio ambiente."),
            new Animales_aprender(
                    12,
                    R.drawable.ganso_canadiense,
                    "Ganso Canadiense",
                    "75-110cm",
                    "3-6.5kg",
                    "Baja",
                    "Cabeza y cuello negros, \"barbilla\" blanca.",
                    "Norteamérica",
                    "Herbívoro",
                    "Forma grandes bandadas en forma de \"V\" durante sus migraciones."),
            new Animales_aprender(
                    13,
                    R.drawable.pez_volador,
                    "Pez Volador",
                    "15-45cm",
                    "30-900gr",
                    "Nula",
                    "Aletas pectorales grandes, se desliza fuera del agua para escapar.",
                    "Océanos Tropicales y Subtropicales del Mundo",
                    "Carnívoro (Plancton)",
                    "No vuela activamente, sino que planea en el aire gracias a su velocidad subacuática."),
            new Animales_aprender(
                    14,
                    R.drawable.fragata_magnifica,
                    "Fragata Magnífica",
                    "1m",
                    "1-1.6kg",
                    "Nula",
                    "Gran envergadura alar, machos con bolsa gular roja inflable.",
                    "Océanos Tropicales (América)",
                    "Carnívoro (Peces)",
                    "La mayor relación de envergadura alar-peso; no aterriza en el agua."),
            new Animales_aprender(
                    15,
                    R.drawable.tucan,
                    "Tucán",
                    "60cm",
                    "600g",
                    "Nula",
                    "Pico grande, ligero y colorido. Plumaje negro con manchas brillantes.",
                    "Selvas de Centro y Sudamérica",
                    "Omnívoro (Frutas, Insectos)",
                    "Utiliza su pico para regular la temperatura y alcanzar frutos."),
            new Animales_aprender(
                    16,
                    R.drawable.quebrantahuesos,
                    "Quebrantahuesos",
                    "1-1.2m",
                    "4.5-7.8kg",
                    "Nula",
                    "Plumaje rojizo, utiliza la altura para dejar caer huesos y abrirlos.",
                    "Montañas de África, Asia y Europa",
                    "Carroñero (Especializado en huesos)",
                    "El único animal conocido cuya dieta principal son los huesos (médula)."),
            new Animales_aprender(
                    17,
                    R.drawable.cuervo,
                    "Cuervo Común",
                    "55-70cm",
                    "0.6-2kg",
                    "Baja",
                    "Plumaje negro brillante, ave grande e inteligente.",
                    "Hemisferio Norte",
                    "Omnívoro",
                    "Una de las aves más inteligentes, capaz de usar herramientas y resolver problemas."),
            new Animales_aprender(
                    18,
                    R.drawable.grulla_de_siberia,
                    "Grulla de Siberia",
                    "1.4m",
                    "5-8kg",
                    "Nula",
                    "Plumaje blanco puro, patas rojas, pico rojo.",
                    "Rusia (Anidación), India y China (Invernada)",
                    "Omnívoro",
                    "Ave migratoria de larga distancia y en peligro crítico."),
            new Animales_aprender(
                    19,
                    R.drawable.chotacabras,
                    "Chotacabras de Noche",
                    "25-28cm",
                    "50-100g",
                    "Nula",
                    "Plumaje críptico (camuflaje), boca muy ancha para cazar insectos en vuelo.",
                    "Europa y Asia",
                    "Carnívoro (Insectívoro)",
                    "Ave nocturna. Famosa por su canto repetitivo y monótono."),
            new Animales_aprender(
                    20,
                    R.drawable.petirrojo_europeo,
                    "Petirrojo Europeo",
                    "12.5-14cm",
                    "16-22g",
                    "Nula",
                    "Pecho de color naranja rojizo muy distintivo.",
                    "Europa y Norte de África",
                    "Omnívoro (Insectos/Semillas)",
                    "Ave muy común, a menudo se acerca a los humanos sin miedo.")
    ));
}