package com.example.proyectofinal;

import java.util.ArrayList;
import java.util.Arrays;

public class ListAnimalesTierra_aprender {
    public static ArrayList<Animales_aprender> listAnimalesTierra_aprender=new ArrayList<>(Arrays.asList(
            new Animales_aprender(
                    1,
                    R.drawable.leon,
                    "León",
                    "1.2m",
                    "150-250kg",
                    "Alta",
                    "Melena distintiva (machos), musculoso, garras retráctiles.",
                    "África Subsahariana",
                    "Carnívoro",
                    "Segundo felino más grande. Vive en grupos sociales llamados manadas."),
            new Animales_aprender(
                    2,
                    R.drawable.elefante,
                    "Elefante africano",
                    "3.2m",
                    "5,000-6,000kg",
                    "Media",
                    "El animal terrestre más grande, orejas grandes, trompa prensil, colmillos.",
                    "Africa Subsahariana",
                    "Herbívoro",
                    "Animal inteligente y social. Crucial dispersor de semillas."),
            new Animales_aprender(
                    3,
                    R.drawable.tigre,
                    "Tigre",
                    "1m",
                    "100-300kg",
                    "Alta",
                    "Felino más grande del mundo. Rayas verticales únicas.",
                    "Asia (Siberia, India, Sumatra)",
                    "Carnívoro",
                    "Depredador solitario y territorial. Seis subespecies vivas."),
            new Animales_aprender(
                    4,
                    R.drawable.oso,
                    "Oso pardo",
                    "1-2m (erguido)",
                    "100-600kg",
                    "Media-Alta",
                    "Cuerpo robusto, joroba muscular, garras fuertes.",
                    "Norteamérica y Eurasia",
                    "Omnívoro",
                    "Puede hibernar. Importante para el equilibrio del ecosistema."),
            new Animales_aprender(
                    5,
                    R.drawable.gorila,
                    "Gorila de montaña",
                    "1.5-1.8m",
                    "140-200kg",
                    "Baja-Media",
                    "Primate más grande, brazos largos, alta inteligencia.",
                    "África Central",
                    "Herbívoro/Frugívoro",
                    "Altamente social. Liderado por un ‘espalda plateada’."),
            new Animales_aprender(
                    6,
                    R.drawable.jirafa,
                    "Jirafa",
                    "5.5m",
                    "800-1,200kg",
                    "Baja",
                    "Cuello extremadamente largo, patrón de manchas.",
                    "África Subsahariana",
                    "Herbívoro",
                    "El mamífero más alto. Come hojas de árboles altos."),
            new Animales_aprender(
                    7,
                    R.drawable.rinoceronte,
                    "Rinoceronte",
                    "1.6m",
                    "800-1,400kg",
                    "Media",
                    "Dos cuernos prominentes, labio superior puntiagudo.",
                    "África Oriental y Meridional",
                    "Herbívoro",
                    "En peligro crítico debido a la caza furtiva."),
            new Animales_aprender(
                    8,
                    R.drawable.zorro,
                    "Zorro rojo",
                    "35-50cm",
                    "2-14kg",
                    "Baja",
                    "Pelaje rojizo, cola larga y tupida con punta blanca.",
                    "América del Norte, Europa, Asia, Australia",
                    "Omnívoro",
                    "Cánido con la distribución más amplia del mundo. Muy adaptable."),
            new Animales_aprender(
                    9,
                    R.drawable.bisonte,
                    "Bisonte",
                    "1.8m",
                    "400-1,000kg",
                    "Media",
                    "Gran joroba, cabeza maciza, pelaje espeso.",
                    "Praderas de Norteamérica",
                    "Herbívoro",
                    "El mamífero terrestre más grande de Norteamérica. Clave para el ecosistema de pastizales."),
            new Animales_aprender(
                    10,
                    R.drawable.panda,
                    "Panda",
                    "0.6-0.9m",
                    "70-120kg",
                    "Nula",
                    "Pelaje blanco y negro distintivo, lento y tranquilo.",
                    "Montañas de China Central",
                    "Herbívoro (Bambú)",
                    "Dieta especializada en bambú. Símbolo de conservación."),
            new Animales_aprender(
                    11,
                    R.drawable.cebra,
                    "Cebra",
                    "1.2-1.4m",
                    "200-450kg",
                    "Baja",
                    "Rayas negras y blancas únicas.",
                    "Pastizales de África Oriental y Meridional",
                    "Herbívoro",
                    "Sus rayas pueden confundir depredadores (efecto deslumbramiento)."),
            new Animales_aprender(
                    12,
                    R.drawable.canguro,
                    "Canguro rojo",
                    "1.5-1.8m",
                    "50-90kg",
                    "Baja",
                    "Patas traseras fuertes para saltar, marsupial.",
                    "Desiertos de Australia",
                    "Herbívoro",
                    "Marsupial más grande del mundo. Puede saltar grandes distancias."),
            new Animales_aprender(
                    13,
                    R.drawable.lobo,
                    "Lobo gris",
                    "0.8m",
                    "30-80kg",
                    "Baja",
                    "Canino esbelto, pelaje denso, mandíbulas fuertes.",
                    "América del Norte, Eurasia, Norte de África",
                    "Carnívoro",
                    "Vive en manadas con estructuras sociales complejas."),
            new Animales_aprender(
                    14,
                    R.drawable.koala,
                    "Koala",
                    "60-85cm",
                    "4-15kg",
                    "Nula",
                    "Marsupial arborícola, orejas grandes y peludas, nariz oscura.",
                    "Australia Oriental y Meridional",
                    "Herbívoro (Eucalipto)",
                    "Dieta altamente especializada en hojas de eucalipto."),
            new Animales_aprender(
                    15,
                    R.drawable.cocodrilo,
                    "Cocodrilo",
                    "3-5m",
                    "225-700kg",
                    "Alta",
                    "Reptil más grande de África, piel escamosa, mandíbulas poderosas.",
                    "África Subsahariana",
                    "Carnívoro",
                    "Caza al acecho y puede permanecer sumergido durante horas."),
            new Animales_aprender(
                    16,
                    R.drawable.cobra,
                    "Cobra real",
                    "3-5m",
                    "Hasta 10kg",
                    "Alta",
                    "Serpiente venenosa más larga del mundo, capucha extensible.",
                    "Asia (India, Sureste Asiático)",
                    "Carnívoro (Ofiófago)",
                    "Veneno mortal. Única serpiente que construye nidos."),
            new Animales_aprender(
                    17,
                    R.drawable.camello,
                    "Camello",
                    "1.8-2m",
                    "400-600kg",
                    "Baja",
                    "Posee una joroba que almacena grasa, patas largas.",
                    "Desiertos de África del Norte y Oriente Medio",
                    "Herbívoro",
                    "Adaptado para almacenar agua y sobrevivir en condiciones extremas del desierto."),
            new Animales_aprender(
                    18,
                    R.drawable.perezoso,
                    "Perezoso",
                    "50-60cm",
                    "2.5-5kg",
                    "Nula",
                    "Movimiento extremadamente lento, garras largas para colgarse.",
                    "Selvas de Centro y Sudamérica",
                    "Herbívoro",
                    "Metabolismo muy lento para digerir hojas de baja energía."),
            new Animales_aprender(
                    19,
                    R.drawable.avestruz,
                    "Avestruz",
                    "2.1-2.8m",
                    "90-130kg",
                    "Baja",
                    "Ave más grande, no voladora, patas largas y fuertes.",
                    "Sabanas de África",
                    "Omnívoro",
                    "Corre a 70 km/h y pone los huevos más grandes del mundo."),
            new Animales_aprender(
                    20,
                    R.drawable.armadillo,
                    "Armadillo",
                    "75-100cm",
                    "25-35kg",
                    "Nula",
                    "Caparazón óseo flexible, garras grandes para excavar.",
                    "Sudamérica (Amazonia, Gran Chaco)",
                    "Carnívoro (Insectívoro)",
                    "Excelente excavador, pasa mucho tiempo bajo tierra.")
    ));
}