package com.example.proyectofinal;

import java.util.ArrayList;
import java.util.Arrays;

public class ListAnimalesAgua_aprender {
    public static ArrayList<Animales_aprender> listAnimalesAgua_aprender=new ArrayList<>(Arrays.asList(
            new Animales_aprender(
                    1,
                    R.drawable.ballena_azul,
                    "Ballena Azul",
                    "25-30m",
                    "100-150T",
                    "Nula",
                    "El animal más grande del planeta. Barbas en lugar de dientes.",
                    "Océanos del Mundo",
                    "Carnívoro (Kril)",
                    "Mamífero marino filtrador. En peligro de extinción."),
            new Animales_aprender(
                    2,
                    R.drawable.tiburon_blanco,
                    "Tiburón Blanco",
                    "4-6m",
                    "700-1,100kg",
                    "Media-Alta",
                    "Cuerpo robusto, dientes afilados y triangulares, gran capacidad de caza.",
                    "Aguas Costeras Templadas del Mundo",
                    "Carnívoro",
                    "Depredador tope. La mayoría de los ataques a humanos son por error de identificación."),
            new Animales_aprender(
                    3,
                    R.drawable.orca,
                    "Orca",
                    "7-9m",
                    "3,000-6,000 kg",
                    "Baja",
                    "Mamífero marino más rápido, coloración negra y blanca distintiva.",
                    "Océanos del Mundo (Preferentemente aguas frías)",
                    "Carnívoro (Peces, Focas, Ballenas)",
                    "El depredador tope marino. Viven en estructuras sociales complejas llamadas vainas."),
            new Animales_aprender(
                    4,
                    R.drawable.delfin,
                    "Delfín Nariz de Botella",
                    "2-4m",
                    "150-650kg",
                    "Nula",
                    "\"Sonrisa\" distintiva, altamente social e inteligente.",
                    "Océanos Templados y Tropicales del Mundo",
                    "Carnívoro (Peces/Calamar)",
                    "Mamífero marino, utilizan la ecolocalización para cazar y navegar."),
            new Animales_aprender(
                    5,
                    R.drawable.pulpo_gigante,
                    "Pulpo Gigante",
                    "3-5m de envergadura",
                    "70kg",
                    "Baja",
                    "8 tentáculos con ventosas, 3 corazones, sangre azul, gran camuflaje.",
                    "Océano Pacífico Norte",
                    "Carnívoro (Crustáceos/Peces)",
                    "Extremadamente inteligente. Pasa la mayor parte de su vida en el fondo marino."),
            new Animales_aprender(
                    6,
                    R.drawable.pez_payaso,
                    "Pez Payaso",
                    "8-15cm",
                    "5-10gr",
                    "Nula",
                    "Coloración naranja con franjas blancas ribeteadas de negro.",
                    "Arrecifes de Coral (Océano Pacífico e Índico)",
                    "Omnívoro",
                    "Vive en simbiosis con anémonas. Cambian de sexo (hermafroditas secuenciales)."),
            new Animales_aprender(
                    7,
                    R.drawable.medusa,
                    "Medusa Melena de León",
                    "Campana de 2m, tentáculos de 36m",
                    "Hasta 200kg",
                    "Media",
                    "La medusa más grande del mundo. Tentáculos urticantes largos y finos.",
                    "Océanos Atlántico y Pacífico Norte",
                    "Carnívoro (Peces pequeños/Kril)",
                    "Sus picaduras pueden ser dolorosas, pero rara vez mortales."),
            new Animales_aprender(
                    8,
                    R.drawable.manati,
                    "Manatí del Caribe",
                    "2.5-4.5m",
                    "200-600kg",
                    "Nula",
                    "Cuerpo grande, cola en forma de remo, lento movimiento.",
                    "Costas, ríos y estuarios del Mar Caribe y Golfo de México",
                    "Herbívoro",
                    "Mamífero marino herbívoro. A veces llamados \"vacas marinas\"."),
            new Animales_aprender(
                    9,
                    R.drawable.pez_espada,
                    "Pez Espada",
                    "3m",
                    "100-500kg",
                    "Baja",
                    "Hocico superior largo y plano (espada). Gran velocidad.",
                    "Océanos Tropicales y Templados del Mundo",
                    "Carnívoro",
                    "Utilizan su \"espada\" para aturdir a sus presas."),
            new Animales_aprender(
                    10,
                    R.drawable.foca,
                    "Foca Arpa",
                    "1.7m",
                    "130kg",
                    "Nula",
                    "Crías de pelaje blanco icónico. Adultos plateados con marca oscura.",
                    "Océano Atlántico Norte y Ártico",
                    "Carnívoro (Peces/Crustáceos)",
                    "Conocidas por criar en grandes colonias sobre el hielo."),
            new Animales_aprender(
                    11,
                    R.drawable.tiburon_ballena,
                    "Tiburón Ballena",
                    "9-18m",
                    "9-20T",
                    "Nula",
                    "Pez más grande del mundo. Piel con patrón de puntos.",
                    "Océanos Tropicales y Cálidos del Mundo",
                    "Carnívoro (Plancton/Peces pequeños)",
                    "Se alimenta por filtración. Es completamente inofensivo para los humanos."),
            new Animales_aprender(
                    12,
                    R.drawable.anguila,
                    "Anguila Eléctrica",
                    "2m",
                    "20kg",
                    "Media",
                    "Cuerpo alargado y cilíndrico. Puede generar descargas eléctricas.",
                    "Ríos del Amazonas y Orinoco (Sudamérica)",
                    "Carnívoro (Peces)",
                    "Usa la electricidad para cazar y defenderse (hasta 600 voltios)."),
            new Animales_aprender(
                    13,
                    R.drawable.pinguino,
                    "Pingüino Emperador",
                    "1.2m",
                    "20-45kg",
                    "Nula",
                    "El pingüino más alto. Plumaje blanco, negro y amarillo-naranja.",
                    "Antártida",
                    "Carnívoro (Peces/Kril)",
                    "El único pingüino que cría en el invierno antártico."),
            new Animales_aprender(
                    14,
                    R.drawable.calamar,
                    "Calamar Gigante",
                    "10-13m",
                    "275kg",
                    "Baja",
                    "Tentáculos con ventosas, ojos más grandes del reino animal.",
                    "Océanos del Mundo (Gran Profundidad)",
                    "Carnívoro",
                    "Animales misteriosos y rara vez vistos vivos."),
            new Animales_aprender(
                    15,
                    R.drawable.estrella_de_mar,
                    "Estrella de Mar",
                    "25-35cm diámetro",
                    "20-80gr",
                    "Media",
                    "Recubierta de espinas tóxicas, posee múltiples brazos.",
                    "Arrecifes de Coral del Pacífico e Índico",
                    "Carnívoro (Coral)",
                    "Su nombre completo es Estrella de mar corona de espinas, su depredación excesiva puede dañar los arrecifes de coral."),
            new Animales_aprender(
                    16,
                    R.drawable.vaca_marina,
                    "Vaquita Marina",
                    "1.5m",
                    "35-50kg",
                    "Baja",
                    "Marsopa pequeña, rostro romo, aleta dorsal triangular, manchas oscuras alrededor de ojos y labios.",
                    "Golfo de California, México",
                    "Carnívoro (peces y calamares)",
                    "Distribución muy restringida, en peligro de extinción. Considerada una especie endémica de México en Baja California."),
            new Animales_aprender(
                    17,
                    R.drawable.pez_luna,
                    "Pez Luna",
                    "3m",
                    "2,300kg",
                    "Nula",
                    "Pez óseo más pesado del mundo. Forma de disco, carece de aleta caudal.",
                    "Océanos Tropicales y Templados del Mundo",
                    "Carnívoro (Medusas)",
                    "A menudo toma el sol en la superficie para calentarse."),
            new Animales_aprender(
                    18,
                    R.drawable.cocodrilo_marino,
                    "Cocodrilo Marino",
                    "4-7m",
                    "400-1,000kg",
                    "Alta",
                    "El reptil más grande del mundo, tolerante al agua salada.",
                    "Sureste Asiático y Australia",
                    "Carnívoro",
                    "El cocodrilo más agresivo y peligroso para el humano."),
            new Animales_aprender(
                    19,
                    R.drawable.nutria_marina,
                    "Nutria Marina",
                    "1.2-1.5m",
                    "14-45kg",
                    "Nula",
                    "Pelaje extremadamente denso, usa herramientas (piedras) para abrir conchas.",
                    "Océano Pacífico Norte",
                    "Carnívoro (Erizos/Moluscos)",
                    "Especie clave que mantiene a raya a los erizos de mar, protegiendo los bosques de algas."),
            new Animales_aprender(
                    20,
                    R.drawable.tortuga_caguama,
                    "Tortuga Caguama",
                    "1m",
                    "80-200kg",
                    "Baja",
                    "Cabeza grande y poderosa, caparazón marrón-rojizo.",
                    "Océanos del Mundo (Excepto Polares)",
                    "Carnívoro (Cangrejos/Moluscos)",
                    "Reptil marino. Migra miles de kilómetros. Vulnerable a la extinción")
    ));
}